### ISSUE TITLE
emit event when graphics loaded

### ISSUE THREAD

**Issue by btfou** [Esri/geojson-layer-js#30]
@alaframboise what do think about an event at the end of `_addGraphics` like `graphics-load`?

If you think it's worth while I'll PR.

**Comment by alaframboise** [comment]
Sounds good.  I would just fire the baseclass event here:

_addGraphics: function (arcgisJson) {
            var i,
                feature,
                graphic;
            // Limit size of data that can be drawn
            if (arcgisJson.length > this._maxDraw) {
                this._drawCountTotal = this._maxDraw;
                console.warn("GeoJsonLayer Warning: Large dataset detected. Only drawing the first " + this._maxDraw + " features!");
            } else {
                this._drawCountTotal = arcgisJson.length;
            }
            // Add graphics to the layer with symbols, project if needed
            for (i = 0; i < this._drawCountTotal; i++) {
                feature = arcgisJson[i];
                // Create graphic - magically sets the geometry type!
                graphic = this._createGraphic(feature);
                // Add to layer
                this._addGraphicToLayer(graphic);
            }
        }

**Comment by alaframboise** [comment]
Implemented in #31.

**Comment by btfou** [comment]
Thanks @alaframboise
