### ISSUE TITLE
GeoJsonLayer not defined

### ISSUE THREAD

**Issue by gursel58** [Esri/geojson-layer-js#32]
I believe I am getting this error due to my inexperience with javascript.
I am trying to inset GeoJsonLayer into a javascript function someone else has written and everytime I run it I get a Referenceerror GeoJsonLayer is not defined

In the html I have:

<script src="../../vendor/terraformer/terraformer.min.js"></script>
<script src="../../vendor/terraformer-arcgis-parser/terraformer-arcgis-parser.min.js"></script>

In the javascript file I have
require(["../../src/geojsonlayer.js"]);

and then in the init function I have

 jsonUrl ="http://opendata.dc.gov/datasets/81a9d9885947483aa2088d81b20bfe66_5.geojson";
var geoJsonLayer = new GeoJsonLayer( {url : jsonUrl} );
map.addLayer(geoJsonLayer);

The javascript code I am using does not have the function (... at the beginning so I suspect it has something to do with how I set it up rather then an issue with the code you have provided.
If you could provide some thoughts how I could get it to work it I would very much appreciate it.

Thanks

**Comment by alaframboise** [comment]
If you paste your url into browser there is no geojson.

http://opendata.dc.gov/datasets/81a9d9885947483aa2088d81b20bfe66_5.geojson

{"status":"processing","processing_time":0,"count":0}

**Comment by gursel58** [comment]
My apolgies I did not update the code after I tried testing aganist a source I thought was there.
the file I am trying to load is 

http://portal.ursel.ca/lightning/nslog/strike.json

and the correct code is 

var    jsonUrl ="http://portal.ursel.ca/lightning/nslog/strike.json";
	var geoJsonLayer = new GeoJsonLayer( {url : jsonUrl} );
	map.addLayer(geoJsonLayer);

**Comment by alaframboise** [comment]
This is an access error. You can see the error in browser console (see below). Your server isn't cors-enabled. You will need to:
1. cors-enable the server, or
2. put the source code on the same server, or 
3. use a proxy in order to access the cross-domain resource.

AL

XMLHttpRequest cannot load http://portal.ursel.ca/lightning/nslog/strike.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://esri.github.io' is therefore not allowed access.
init.js:188 mw @ init.js:188
geojsonlayer.js:203 GeoJsonLayer Error: Couldn't load GeoJSON. Check url. File must be on the same domain or server must be CORS enabled.

RequestError: Unable to load http://portal.ursel.ca/lightning/nslog/strike.json status: 0

**Comment by gursel58** [comment]
I thought I had my apache setup for CORS, will work on that.

Does geojsonlayer send the data to http://esri.github.io for processing before loading it into the arcgis api map ??

**Comment by alaframboise** [comment]
Here's how it works. The page loads the ArcGIS javascript from arcgis.com and the geojson-layer-js code and html from esri.github.io. The javascript then makes an async http request to get the geojson resources from the cors-enabled server you specify.

**Comment by gursel58** [comment]
Ok I copied the example (made the necessary changes) and have it load a geojson file (produced from POSTGIS) and everything works.
I then use the original javascript app with the same file and get the sam Referrenceerror GeoJsonLayer is not defined.

Here is the code that adds the layer.

var    jsonUrl ="../../geojson/data/strike2.json";
	var geoJsonLayer = new GeoJsonLayer( {url : jsonUrl} );
	map.addLayer(geoJsonLayer);

I am fairly certain it is how I "include" the geojsonlayer.js file with the other requires

dojo.require("esri.map");
dojo.require("esri.layers.KMLLayer");
dojo.require("esri.layers.osm");
dojo.require("esri.layers.WebTiledLayer");
dojo.require("esri.layers.FeatureLayer");
dojo.require("esri.symbol");
dojo.require("esri.dijit.Scalebar");
//dojo.require("esri.tasks.BufferParameters");
dojo.require("esri.tasks.GeometryService");
dojo.require("esri.config");
dojo.require("esri.layers.GeoRSSLayer");
dojo.require("esri.Color");
dojo.require("esri.layers.GraphicsLayer");
dojo.require("esri.InfoTemplate");
dojo.require("esri.renderers.SimpleRenderer");
dojo.require("esri.layers.ArcGISDynamicMapServiceLayer");
//dojo.require("/src/geojsonlayer");
esriConfig.defaults.io.corsEnabledServers.push("sampleserver6.arcgisonline.com");
dojo.require("esri.symbols.PictureMarkerSymbol");
require(["../../src/geojsonlayer.js"]);
dojo.addOnLoad(init);

To test the example code
http://portal.ursel.ca/geojson/geojsonlayer.html

Otherwise it is exactly what I need.

**Comment by gursel58** [comment]
I was able to get things working by:

in geojsonlayer.js change the function declaration to:

 function (declare, Graphic, GeoJsonLayer, InfoTemplate, graphicsUtils, Color, SimpleMarkerSymbol,
        SimpleLineSymbol, SimpleFillSymbol, SimpleRenderer, SpatialReference, webMercatorUtils, esriRequest, esriConfig, Url, lang
    ) {
    return declare([GeoJsonLayer], {

in the html page add dojoConfig
<script>
     dojoConfig={
	        packages: [{
			    name: "GeoJsonLayer",
				location: "/src"
				}]
				};
</script>	

in the javascript file 
add in a dojo.require
dojo.require("GeoJsonLayer.geojsonlayer");

and create the layer 
jsonUrl = "http://portal.ursel.ca/lightning/nslog/strike.json";
	geoJsonLayer = new GeoJsonLayer.geojsonlayer( {url : jsonUrl} );
	map.addLayer(geoJsonLayer);

and everything worked. 
Thanks for your help.

**Comment by GB11111** [comment]
Gursel - I'm having the same issue you had, but your fix isn't working for me. I made the changes except for one part: can you explain what configurations to add where you say "in the html page add dojoConfig"?  Thanks.

**Comment by gursel58** [comment]
I am having to dig back in memory, I have since rewritten the entire system (using OL3 now)
As near as I can recall there are three pieces that had to link together

IN my HTML page when I was loading all of the javascript and css files I define the dojo config like this
<script>
     dojoConfig={
	        packages: [{
			    name: "GraphicsLayer",
				location: "/NDisplay2Dev/jquery"
				}]
				};
</script>	
--I have the geojsonlayer.js file inside the NDisplay2Dev/jquery directory , and this just points it to it.

In the beginning of my javascript file that does everything I have all of the dojo.requires including

 dojo.require("GraphicsLayer.geojsonlayer");	

In the beginning of the geojsonlayer.js file there is a function declaration which returns a  GraphicsLayer

function (declare, Graphic, GraphicsLayer, InfoTemplate, graphicsUtils, Color, SimpleMarkerSymbol,
        SimpleLineSymbol, SimpleFillSymbol, SimpleRenderer, SpatialReference, webMercatorUtils, esriRequest, esriConfig, Url, lang, PictureMarkerSymbol
    ) {
    return declare([GraphicsLayer], {

therefore everything is tied together.
Hopefully this helps
Greg

**Comment by gursel58** [comment]
Sorry it took out the dojoConfig piece (probably because I had it surrounded with script tags
here it is...add the script tags before and after

 dojoConfig={
	        packages: [{
			    name: "GraphicsLayer",
				location: "/NDisplay2Dev/jquery"
				}]
				};

**Comment by GB11111** [comment]
Gursel - Apologies for me not getting back sooner, I was diverted to another task. 

I tried your latest code but still getting the "TypeError: GeoJsonLayer is not a constructor" error. It appears from your more recent post that you tried something different, as on the Jun 4 post you had modified the code to "return declare([GeoJsonLayer]", whereas the latest is the original code "return declare([GraphicsLayer]". Staying w/ the original code seems the better way to go, so I did try injecting "GraphicsLayer.geojsonlayer" and modifying the dojoConfig, but alas, no success.

I know you went a different route w/ the OpenLayers, but if you have any additional tribal knowledge that might help please suggest away. :) Thanks.

GB

**Comment by GB11111** [comment]
Just a note that I did solve this issue.  The Dojo dependency injection (part of its 'require' function) was for whatever reason very sensitive to the GeoJsonLayer's call order.  When I placed it 2nd in the array, just after the "esri/map" array item, everything worked fine. See below for an example.

require([ "esri/map", "./vendor/geojson-layer-js/geojsonlayer.js", ...."dojo/domReady!"], function(Map, GeoJsonLayer,...., dom) {
     ...
}

**Comment by ahmadalibaloch** [comment]
For me it's searching for `geojsonlayer.js` in an known location. I am using webpack, i think its searching for the file from dist folder. Any one can help in how to bundle geojsonlayer.js to a location where thie dojoRequire is looking for?
