### ISSUE TITLE
Point to 4.x GeoJSON Layer in README

### ISSUE THREAD

**Issue by mpayson** [Esri/geojson-layer-js#44]
The 4.x JS API now has a native [GeoJSON layer](https://developers.arcgis.com/javascript/latest/sample-code/layers-geojson/index.html), can we update the README to point here for the latest and greatest? And maybe flag this as not actively maintained in favor of that API?

It would also offer a solution for a few of the issues here (display over 1K features, handle different projections, etc)

cc @alaframboise

**Comment by alaframboise** [comment]
Done. Thanks!
